### ISSUE TITLE
Align Bouncycastle version

### ISSUE THREAD

**Issue by egelke** [egelke/eHI#2]

**Comment by egelke** [comment]
Hi,

I have a new problem now : I can unseal the message but when I use the full flow of getting data... I have the following problem :

  *   EGELKE.EHealth.Client.PKI needs BouncyCastle.Crypto 1.8.5
  *   But EGELKE.Ehealth.Etee.Crypto needs BouncyCastle.Crypto 1.8.6

So when I use those 2 packages in the same project, I have a problem : if I use BouncyCastle 1.8.5 I have a missing assembly for Etee.Crypto : missing 1.8.6
And if I use BouncyCastle 1.8.6 I have a missing assembly for Etee.PKI : missing 1.8.5

What can I do ?

I update all EGELKE packages with last BETA version.

Thank you,
Best Regards,

Nicolas Giannone

**Comment by egelke** [comment]
Releasing Beta5 with updated BouncyCastle

**Comment by egelke** [comment]
please let me know if you can user PKI Beta5 with Crypto Beta3 (which refers to PKI Beta4 nuget package but same assembly version)

**Comment by giannone-nicolas** [comment]
everything works : pki with crypto and both with the same version of bouncy castle. Now the full flow of our call is working. Thank you for your fix.
