### ISSUE TITLE
Certificate chain validation fails when unsealing

### ISSUE THREAD

**Issue by thomasdc** [egelke/eHI#3]
First of all, thanks for creating this library, it's a great help!

I've encountered an exception in the latest version (2.2.0) when unsealing a response from KGSS in eHealth's acceptance environment (see below).

Apparently the validation fails because the `signingTime` lies too far in the future. I guess the hardcoded `ClockSkewness` in `X509CertificateHelper` is insufficient.

A solution would be to simply increase it (2 minutes?) or make it configurable.

What's your take on this?

![image](https://user-images.githubusercontent.com/1496708/104478444-9662b600-55c2-11eb-81ea-a4982a08f24c.png)

**Comment by egelke** [comment]
I see, if I recall correctly eHealth ACC sometimes has an issue with clock drift.  I'll change the skewness to 5 min; which is quite acceptable

**Comment by egelke** [comment]
Publishing a new version of the PKI lib, I'll publish a new version of E2EE lib right after this with the updated ref.

**Comment by thomasdc** [comment]
Thanks!
